<%@ Page Language="C#" AutoEventWireup="true" CodeFile="test-history.aspx.cs" Inherits="shynet_test_history" MaintainScrollPositionOnPostback="True" %>
<!DOCTYPE html>
<html lang="en">
<head runat="server">
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student History</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container body-content" style="margin-top:10px;">
    <form runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server" />

        <b><asp:Literal ID="litHeading" runat="server" /></b><br/>

        <asp:SqlDataSource ID="srcHistory" runat="server" 
            ConnectionString="<%$ ConnectionStrings:Heroku %>" 
            ProviderName="<%$ ConnectionStrings:Heroku.ProviderName %>"
            SelectCommand="SELECT * FROM old_show_history(@student_id)" 
            SelectCommandType="Text"
            DeleteCommand="old_delete_history"
            DeleteCommandType="StoredProcedure"
            UpdateCommand="old_update_history"
            UpdateCommandType="StoredProcedure"
            >
            <SelectParameters>
                <asp:Parameter Name="student_id" DbType="Guid" Direction="Input" />
            </SelectParameters>
            <DeleteParameters>
                <asp:Parameter DbType="String" Direction="Input" />
                <asp:Parameter DbType="Guid" Direction="Input" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter DbType="String" Direction="Input" />
                <asp:Parameter DbType="Guid" Direction="Input" />
                <asp:Parameter DbType="Date" Direction="Input" />
                <asp:Parameter DbType="Guid" Direction="Input" />
                <asp:Parameter DbType="Guid" Direction="Input" />
                <asp:Parameter DbType="Guid" Direction="Input" />
                <asp:Parameter DbType="Int16" Direction="Input" />
                <asp:Parameter DbType="Guid" Direction="Input" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <asp:GridView ID="gvHistory"
            CssClass="table table-striped table-hover table-condensed table-bordered"
            AllowPaging="True"
            AutoGenerateColumns="False"
            DataSourceID="srcHistory"
            DataKeyNames="transaction_type,id"
            PageSize="20" 
            runat="server"
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" 
            OnRowDeleting="gvHistory_RowDeleting"
            OnRowCancelingEdit="gvHistory_RowCanceling"
            OnRowEditing="gvHistory_RowEditing"
            OnRowDataBound="gvHistory_RowDataBound"
            PagerSettings-PageButtonCount="5">
            <Columns>
                <asp:BoundField DataField="transaction_type" Visible="false" ReadOnly="true" />
                <asp:BoundField DataField="id" Visible="false" ReadOnly="true" />
                <asp:TemplateField HeaderText="Date" ItemStyle-Width="90px">
                    <EditItemTemplate>
                        <asp:TextBox ID="txtClassDate" CssClass="form-control" TextMode="Date" Text='<%# Bind("transaction_date","{0:yyyy-MM-dd}") %>' runat="server" Width="160px" AutoPostBack="True" />
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="transaction_date" runat="server" Text='<%# Bind("transaction_date","{0:d}") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Description">
                    <EditItemTemplate>
                        <asp:Label ID="lblInstructor" runat="server" Text='<%# Bind("instructor_id") %>'></asp:Label>
                        <asp:dropdownlist id="lstInstructor" CssClass="form-control" runat="server" AutoPostBack="true" />
                        <asp:Label ID="lblClass" runat="server" Text='<%# Bind("class_id") %>'></asp:Label>
                        <asp:Label ID="lblLocation" runat="server" Text='<%# Bind("location_id") %>'></asp:Label>
                        <asp:Label ID="lblPaymentType" runat="server" Text='<%# Bind("payment_type_id") %>'></asp:Label>
                        <!-- Where the original DropdownLists go -->
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblWhat" runat="server" Text='<%# Bind("what") %>'></asp:Label>
                    </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" />
                </asp:TemplateField>
                <asp:BoundField DataField="quantity" HeaderText="Qty" ControlStyle-CssClass="form-control" HeaderStyle-CssClass="text-center" ItemStyle-HorizontalAlign="Right" ItemStyle-Width="60px" />
                <asp:BoundField DataField="balance" HeaderText="Balance" ItemStyle-HorizontalAlign="Right" ItemStyle-Width="60px" ReadOnly="True" />
            </Columns>
        </asp:GridView>
    </form>
    </div>
</body>
</html>
