using System;
using System.Web.UI.WebControls;

public partial class shynet_history : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        srcHistory.SelectParameters[0].DefaultValue = Request.QueryString["id"];
        litHeading.Text = Request.QueryString["name"];

        if (User.Identity.Name == "SHYNET\\shy")
        {
            dgHistory.AutoGenerateDeleteButton = false;
            dgHistory.AutoGenerateEditButton = false;
        }
    }

    protected void dgHistory_RowDeleting(object sender, GridViewDeleteEventArgs e)
    {
        srcHistory.DeleteParameters[0].DefaultValue = dgHistory.DataKeys[e.RowIndex].Values["transaction_type"].ToString(); // Transaction type (P or A)
        srcHistory.DeleteParameters[1].DefaultValue = dgHistory.DataKeys[e.RowIndex].Values["id"].ToString();  // id
        //TODO: Rebind main DataView in case class was deleted from currently displayed one
    }

    protected void dgHistory_RowCanceling(object sender, GridViewCancelEditEventArgs e)
    {
        // I probably don't need to do this since I'm using automatic binding
        //dgHistory.EditIndex = -1;
        //dgHistory.DataBind();
    }

    protected void dgHistory_RowEditing(object sender, GridViewEditEventArgs e)
    {

        if (dgHistory.DataKeys[e.NewEditIndex].Values["transaction_type"].ToString() == "A")
            ((BoundField)dgHistory.Columns[4]).ReadOnly = true;
        else
            ((BoundField)dgHistory.Columns[4]).ReadOnly = false;
    }

    protected void dgHistory_RowDataBound(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.RowState == DataControlRowState.Edit)
        {
            DropDownList lstPaymentTypes = (DropDownList)e.Row.FindControl("lstPaymentTypes");
            if (dgHistory.DataKeys[e.Row.RowIndex].Values["transaction_type"].ToString() == "A")
                lstPaymentTypes.Visible = false;
            else
                lstPaymentTypes.Visible = true;
        }
    }

}